config/routes.rb
TrelloClone::Application.routes.draw do
  resources :users, :only => [:new, :create, :show, :edit, :update]
  resources :boards do
    resources :board_memberships, :only => [:create]
    resources :board_admins, :only => [:create]
    resources :lists, :only => [:create, :new]
  end
  resources :lists, :only => [:show, :edit, :update, :destroy] do
    resources :cards, :only => [:create, :new]
  end
  resources :cards, :only => [:show, :edit, :update, :destroy] do
    resources :comments, :only => [:create]
    resources :checklists, :only => [:new, :create]
  end
  resources :checklists, :only => [:show, :edit, :update, :destoy] do
    resources :items, :only => [:create]
  end

  resources :items, :only => [:update, :destroy]

  resource :session, :only => [:new, :create, :destroy]

  root :to => "static_pages#index"

  namespace :api, :default => :json do
    resources :boards, :only => [:index, :show, :create, :update, :destroy] do
      resources :board_memberships, :only => [:create]
      resources :board_admins, :only => [:create]
      resources :lists, :only => [:create, :index]
    end
    resources :lists, :only => [:show, :update, :destroy] do
      resources :cards, :only => [:create]
    end
    resources :cards, :only => [:show, :update, :destroy] do
      resources :comments, :only => [:create]
      resources :checklists, :only => [:create]
    end
    resources :checklists, :only => [:show, :update, :destoy] do
      resources :items, :only => [:create]
    end
    resources :users, :only => [:index]

    resources :items, :only => [:update, :destroy]
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :position

  validates :name, :board, :position, :presence => true
  belongs_to :board, :inverse_of => :lists
  has_many :cards,
           :order => "position ASC",
           :inverse_of => :list,
           :dependent => :destroy
end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApplicationController

  before_filter :require_login

  def index
    @board = Board.find_by_id(params[:board_id])
    @lists = @board.lists.includes(
        :cards => { :checklists =>  :items , :comments => {}}
        )
    render "api/lists/index"
  end

  def create
    @list = List.new(params[:list])
    @board = Board.find_by_id(params[:board_id])
    @list.board = @board
    @list.position = @board.lists.length.to_f
    @list.archived = false
    if @list.save
      render :json => @list
    else
      render :json => @list.errors.full_messages
    end
  end

  def show
    @list = List.where(:id => params[:id]).includes(
        :cards => { :checklists => :items, :comments => {} }
        ).first
    if @list
      render "api/lists/show"
    else
      render :json => "404 Not Found", :status => 404
    end
  end

  def update
    @list = List.where(:id => params[:id]).includes(
        :cards => { :checklists => :items, :comments => {} }
        ).first
    if @list.update_attributes(params[:list])
      render "api/lists/show"
    else
      render :json => @list.errors.full_messages
    end
  end

  def destroy
    @list = List.find_by_id(params[:id])
    @board = @list.board
    @list.destroy
    render :json => @board
  end

  private



end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_filter :require_login

  def new
    @board = Board.find_by_id(params[:board_id])
    if @board && is_member?(@board, current_user)
      render :new
    else
      render :text => "404 Not Found", :status => 404
    end
  end

  def create
    @list = List.new(params[:list])
    @board = Board.find_by_id(params[:board_id])
    @list.board = @board
    @list.position = @board.lists.length.to_f
    @list.archived = false
    if @list.save
      redirect_to list_url(@list)
    else
      flash.now[:notices] = @list.errors.full_messages
      render :new
    end
  end

  def show
    @list = List.find_by_id(params[:id]);
    if @list
      render :show
    else
      render :text => "404 Not Found", :status => 404
    end
  end

  def edit
    @list = List.find_by_id(params[:id])
    if @list
      render :edit
    else
      render :text => "404 Not Found", :status => 404
    end
  end

  def update
    @list = List.find_by_id(params[:id])
    lists = @list.board.lists
    new_position = params[:list][:position].to_i
    if new_position == 0
      position_value = lists[0].position - 1
    elsif new_position == lists.length - 1
      position_value = (lists.length + lists[new_position].position) / 2
    else
      position_value == (lists[new_position - 1].position +
                         lists[new_position].position) / 2
    end
    params[:list][:position] = position_value
    if @list.update_attributes(params[:list])
      redirect_to list_url(@list)
    else
      flash.now[:notices] = @list.errors.full_messages
      render :edit
    end
  end

  def destroy
    @list = List.find_by_id(params[:id])
    @board = @list.board
    @list.destroy
    redirect_to board_url(@board)
  end

  private



end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/edit.html.erb
<%= link_to "<-Back", list_url(@list) %>
<h2>Edit List</h2>

<form action="<%= list_url(@list) %>" method="POST">
  <input type="hidden" name="authenticity_token"
           value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PUT">
  <label for="list_name">List Name</label>
  <input type="text" id="list_name" name="list[name]" value="<%= @list.name %>">
  <br>
  <label for="list_position">List Position</label>
  <select id="list_position" name="list[position]">
    <% @list.board.lists.length.times do |position| %>
      <option <%= "selected" if @list.board.lists[position].id == @list.id %> value="<%= position %>"><%= position + 1 %></option>
    <% end %>
    <br>
  <input type="submit" value="Update List">
</form>

app/views/lists/new.html.erb
<%= link_to "<-Back", board_url(@board) %>
<h2>Add a list</h2>

<form action="<%= board_lists_url(@board) %>" method="POST">
  <input type="hidden" name="authenticity_token"
           value="<%= form_authenticity_token %>">
  <label for="list_name">List Name</label>
  <input type="text" id="list_name" name="list[name]">
  <input type="submit" value="Add List">
</form>

app/views/lists/show.html.erb
<%= link_to "<-#{@list.board.name}", board_url(@list.board) %>
<h2><%= @list.name %></h2>

<ul>
  <% @list.cards.each do |card| %>
  <li><%= link_to card.name, card_url(card) %></li>
  <% end %>
</ul>

<%= link_to "New Card", new_list_card_url(@list) %>
<br>
<%= link_to "Edit List", edit_list_url(@list) %>