config/routes.rb
TrelloClone::Application.routes.draw do
  resources :users, :only => [:new, :create, :show, :edit, :update]
  resources :boards do
    resources :board_memberships, :only => [:create]
    resources :board_admins, :only => [:create]
    resources :lists, :only => [:create, :new]
  end
  resources :lists, :only => [:show, :edit, :update, :destroy] do
    resources :cards, :only => [:create, :new]
  end
  resources :cards, :only => [:show, :edit, :update, :destroy] do
    resources :comments, :only => [:create]
    resources :checklists, :only => [:new, :create]
  end
  resources :checklists, :only => [:show, :edit, :update, :destoy] do
    resources :items, :only => [:create]
  end

  resources :items, :only => [:update, :destroy]

  resource :session, :only => [:new, :create, :destroy]

  root :to => "static_pages#index"

  namespace :api, :default => :json do
    resources :boards, :only => [:index, :show, :create, :update, :destroy] do
      resources :board_memberships, :only => [:create]
      resources :board_admins, :only => [:create]
      resources :lists, :only => [:create, :index]
    end
    resources :lists, :only => [:show, :update, :destroy] do
      resources :cards, :only => [:create]
    end
    resources :cards, :only => [:show, :update, :destroy] do
      resources :comments, :only => [:create]
      resources :checklists, :only => [:create]
    end
    resources :checklists, :only => [:show, :update, :destoy] do
      resources :items, :only => [:create]
    end
    resources :users, :only => [:index]

    resources :items, :only => [:update, :destroy]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic :size => 20, :default => "identicon"

  attr_accessible :avatar, :email, :name, :password, :username
  attr_reader :password

  validates :email, :username, :password_digest, :presence => true
  validates :password, :length => { :minimum => 6 }, :on => :create
  validates :email, :uniqueness => true

  before_validation  :reset_session_token, :on => :create

  has_many :memberships, :class_name => "BoardMembership", :inverse_of => :user
  has_many :member_boards, :through => :memberships, :source => :board
  has_many :administrations, :class_name => "BoardAdmin", :inverse_of => :user
  has_many :administered_boards, :through => :administrations, :source => :board

  def self.find_by_credentials(params)
    user = User.find_by_email(params[:email])
    return user if user && user.is_password?(params[:password])
    nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.reset_session_token
    self.save!
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  before_filter :require_login, :only => [:edit, :update]

  def index
    @users = User.all
    render "/api/users/index"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :require_login, :only => [:edit, :update]

  def new
    @user = User.new()
    render :new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      login!(@user)
      redirect_to :root
    else
      flash.now[:notices] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    if @user
      render :show
    else
      render :text => "404 Not Found", :status => 404
    end

  end

  def edit
    @user = User.find_by_id(params[:id])
    if @user && @user.id == current_user.id
      render :edit
    else
      render :text => "404 Not Found", :status => 404
    end
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user.update_attributes(params[:user])
      login!(@user)
      redirect_to :root
    else
      flash.now[:notices] = @user.errors.full_messages
      render :edit
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="authenticity_token"
           value="<%= form_authenticity_token %>">
  <% if @user.persisted? %>
    <input type="hidden" name="_method" value="PUT">
  <%end%>
  <label for="user_email">Email</label>
  <input type="text" id="user_email" name="user[email]"
    value=<%= @user.email %>>
    <br>
  <label for="user_username">Username</label>
  <input type="text" id="user_username" name="user[username]"
    value=<%=@user.username %>>
    <br>
  <% if !@user.persisted? %>
    <label for="user_password">Password</label>
    <input type="password" id="user_password" name="user[password]">
  <% end %>
  <input type="submit" value="<%= submit_verb %>">
</form>

app/views/users/edit.html.erb
<% submit_verb = "Edit Account"%>
<h2>Edit Account</h2>
<%= render "form", {:action_url => user_url(@user), :submit_verb => submit_verb} %>

app/views/users/new.html.erb
<div class="col-xs-4 col-xs-offset-4 jumbotron">
	<h3>Sign In</h3>
	<form action="<%= users_url %>" method="POST">
	  <input type="hidden" name="authenticity_token"
	           value="<%= form_authenticity_token %>">
		<div class="form-group">
		  <label for="user_email">Email</label>
		  <input type="text" class="form-control" id="user_email"
				name="user[email]" placeholder="Email">
		</div>
		<div class="form-group">
		  <label for="user_username">Username</label>
		  <input type="text" class="form-control" id="user_username"
				name="user[username]" placeholder="Username">
		</div>
		<div class="form-group">
	    <label for="user_password">Password</label>
	    <input type="password" class="form-control" id="user_password"
					name="user[password]" placeholder="Password">
		</div>
	  <input type="submit" class="btn btn-primary" value="Create New Account">
	</form>
</div>

app/views/users/show.html.erb
<h2><%= @user.username %>'s Page</h2>

<% if current_user && current_user.id = @user.id%>
  <%= link_to "Edit User", edit_user_url(@user) %>
<% end %>