config/routes.rb
TrelloClone::Application.routes.draw do
  resources :users, :only => [:new, :create, :show, :edit, :update]
  resources :boards do
    resources :board_memberships, :only => [:create]
    resources :board_admins, :only => [:create]
    resources :lists, :only => [:create, :new]
  end
  resources :lists, :only => [:show, :edit, :update, :destroy] do
    resources :cards, :only => [:create, :new]
  end
  resources :cards, :only => [:show, :edit, :update, :destroy] do
    resources :comments, :only => [:create]
    resources :checklists, :only => [:new, :create]
  end
  resources :checklists, :only => [:show, :edit, :update, :destoy] do
    resources :items, :only => [:create]
  end

  resources :items, :only => [:update, :destroy]

  resource :session, :only => [:new, :create, :destroy]

  root :to => "static_pages#index"

  namespace :api, :default => :json do
    resources :boards, :only => [:index, :show, :create, :update, :destroy] do
      resources :board_memberships, :only => [:create]
      resources :board_admins, :only => [:create]
      resources :lists, :only => [:create, :index]
    end
    resources :lists, :only => [:show, :update, :destroy] do
      resources :cards, :only => [:create]
    end
    resources :cards, :only => [:show, :update, :destroy] do
      resources :comments, :only => [:create]
      resources :checklists, :only => [:create]
    end
    resources :checklists, :only => [:show, :update, :destoy] do
      resources :items, :only => [:create]
    end
    resources :users, :only => [:index]

    resources :items, :only => [:update, :destroy]
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :archived, :description, :due_date, :list_id, :name, :position
  validates :list, :name, :presence => true

  belongs_to :list, :inverse_of => :cards
  has_many :comments, :inverse_of => :card, :dependent => :destroy
  has_many :checklists,
           :order => "position ASC",
           :inverse_of => :card,
           :dependent => :destroy
end

app/controllers/api/cards_controller.rb
class Api::CardsController < ApplicationController

  before_filter :require_login

  def create
    @card = Card.new(params[:card])
    @list = List.find_by_id(params[:list_id])
    @card.list = @list
    @card.position = 0
    @card.position = @list.cards.last.position + 1 if @list.cards.last
    if @card.save
      render :json => @card
    else
      render :json => @card.errors.full_messages
    end
  end

  def show
    @card = Card.find_by_id(params[:id])
    if @card
      render :json => @card, :include => [:comments, :checklists]
    else
      render :json => "404 Not Found", :status => 404
    end
  end

  def update
    @card = Card.find_by_id(params[:id])
    if @card.update_attributes(params[:card])
      render :json => @card, :include => [:comments, :checklists]
    else
      render :json => @card.errors.full_messages
    end
  end

  def destroy
    @card = Card.find_by_id(params[:id])
    @card.destroy
    head :ok
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  before_filter :require_login

  def new
    @list = List.find_by_id(params[:list_id])
    if @list && is_member?(@list.board, current_user)
      render :new
    else
      render :text => "404 Not Found", :status => 404
    end
  end

  def create
    @card = Card.new(params[:card])
    @list = List.find_by_id(params[:list_id])
    @card.list = @list
    @card.position = @list.cards.length
    if @card.save
      redirect_to card_url(@card)
    else
      flash.now[:notices] = @card.errors.full_messages
      render :new
    end
  end

  def show
    @card = Card.find_by_id(params[:id])
    if @card
      render :show
    else
      render :text => "404 Not Found", :status => 404
    end
  end

  def edit
    @card = Card.find_by_id(params[:id])
    if @card
      render :edit
    else
      render :text =>  "404 Not Found", :status => 404
    end
  end

  def update
    @card = Card.find_by_id(params[:id])
    cards = @card.list.cards
    new_position = params[:card][:position].to_i
    if new_position == 0
      position_value = cards[0].position - 1
    elsif new_position == cards.length - 1
      position_value = (cards.length + cards[new_position].position) / 2
    else
      position_value == (cards[new_position - 1].position +
                         cards[new_position].position) / 2
    end
    params[:card][:position] = position_value
    if @card.update_attributes(params[:card])
      redirect_to card_url(@card)
    else
      flash.now[:notices] = @card.errors.full_messages
      render :edit
    end
  end

  def destroy
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/edit.html.erb
<%= link_to "<- Back to Card", card_url(@card) %>

<h2>Edit Card</h2>

<form action="<%= card_url(@card) %>" method="POST">
  <input type="hidden" name="authenticity_token"
           value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PUT">
  <label for="card_name">Card Name</label>
  <input type="text" id="card_name" name="card[name]" value="<%= @card.name %>">
  <br>
  <label for="card_description">Card Description</label>
  <input type="text" id="card_description" name="card[description]" value="<%= @card.description %>">
  <br>
  <label for="card_due_date">Due Date</label>
  <input type="date" id="card_due_date" name="card[due_date]" value="<%= @card.due_date %>">
  <br>
  <label for="card_position">Card Position</label>
  <select id="card_position" name="card[position]">
    <% @card.list.cards.length.times do |position| %>
      <option <%= "selected" if @card.list.cards[position].id == @card.id %> value="<%= position %>"><%= position + 1 %></option>
    <% end %>
    <br>
  <input type="submit" value="Update Card">
</form>

app/views/cards/new.html.erb
<%= link_to "<-Back", list_url(@list) %>
<h2>Add a card</h2>

<form action="<%= list_cards_url(@list) %>" method="POST">
  <input type="hidden" name="authenticity_token"
           value="<%= form_authenticity_token %>">
  <label for="card_name">Card Name</label>
  <input type="text" id="card_name" name="card[name]">
  <input type="submit" value="Add Card">
</form>

app/views/cards/show.html.erb
<%= link_to "<- #{@card.list.name}",  list_url(@card.list) %>

<h2><%= @card.name %></h2>
<% if @card.due_date %>
  <h4>Due Date: <%= @card.due_date %></h4>
<% end %>

<p><%= @card.description %></p>

<h4>Checklists</h4>
<ul>
  <% @card.checklists.each do |checklist| %>
    <li><%= link_to checklist.name, checklist_url(checklist) %></li>
  <% end %>
</ul>

<%= link_to "New Checklist", new_card_checklist_url(@card) %>
<h4>Comments</h4>

<ul>
  <% @card.comments.each do |comment| %>
  <li><%= comment.body %> -- <strong><%= comment.user.username %></strong></li>
  <% end %>
</ul>

<%= render "comments/form" %>

<%= link_to "Edit Card", edit_card_url(@card) %>