config/routes.rb
TrelloClone::Application.routes.draw do
  resources :users, :only => [:new, :create, :show, :edit, :update]
  resources :boards do
    resources :board_memberships, :only => [:create]
    resources :board_admins, :only => [:create]
    resources :lists, :only => [:create, :new]
  end
  resources :lists, :only => [:show, :edit, :update, :destroy] do
    resources :cards, :only => [:create, :new]
  end
  resources :cards, :only => [:show, :edit, :update, :destroy] do
    resources :comments, :only => [:create]
    resources :checklists, :only => [:new, :create]
  end
  resources :checklists, :only => [:show, :edit, :update, :destoy] do
    resources :items, :only => [:create]
  end

  resources :items, :only => [:update, :destroy]

  resource :session, :only => [:new, :create, :destroy]

  root :to => "static_pages#index"

  namespace :api, :default => :json do
    resources :boards, :only => [:index, :show, :create, :update, :destroy] do
      resources :board_memberships, :only => [:create]
      resources :board_admins, :only => [:create]
      resources :lists, :only => [:create, :index]
    end
    resources :lists, :only => [:show, :update, :destroy] do
      resources :cards, :only => [:create]
    end
    resources :cards, :only => [:show, :update, :destroy] do
      resources :comments, :only => [:create]
      resources :checklists, :only => [:create]
    end
    resources :checklists, :only => [:show, :update, :destoy] do
      resources :items, :only => [:create]
    end
    resources :users, :only => [:index]

    resources :items, :only => [:update, :destroy]
  end
end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
  attr_accessible :name, :position

  validates :name, :presence => true

  belongs_to :card, :inverse_of => :checklists
  has_many :items, :inverse_of => :checklist
end

app/controllers/api/checklists_controller.rb
class Api::ChecklistsController < ApplicationController

  def create
    @card = Card.find_by_id(params[:card_id])
    @checklist = Checklist.new(params[:checklist])
    @checklist.card = @card
    @checklist.position = @card.checklists.length
    if @checklist.save
      render :json => @checklist
    else
      render :json => @checklist.errors.full_messages
    end
  end

  def show
    @checklist = Checklist.find_by_id(params[:id])
    if @checklist
      render :json => @checklist, :include => :items
    else
      render :json => "404 Not Found", :status => 404
    end
  end

  def update
    @checklist = Checklist.find_by_id(params[:id])
    if @checklist.update_attributes(params[:checklist])
      render :json => @checklist, :include => :items
    else
      render :json => @checklist.errors.full_messages
    end
  end


  def destroy
  end
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController

  def new
    @card = Card.find_by_id(params[:card_id])
    if @card
      render :new
    else
      render :text => "404 Not Found", :status => 404
    end
  end

  def create
    @card = Card.find_by_id(params[:card_id])
    @checklist = Checklist.new(params[:checklist])
    @checklist.card = @card
    @checklist.position = @card.checklists.length
    if @checklist.save
      redirect_to checklist_url(@checklist)
    else
      flash.now[:notices] = @checklist.errors.full_messages
      render :new
    end
  end

  def show
    @checklist = Checklist.find_by_id(params[:id])
    if @checklist
      render :show
    else
      render :text => "404 Not Found", :status => 404
    end
  end

  def edit
    @checklist = Checklist.find_by_id(params[:id])
    if @checklist
      render :edit
    else
      render :text => "404 Not Found", :status => 404
    end
  end

  def update
    @checklist = Checklist.find_by_id(params[:id])
    checklists = @checklist.card.checklists
    new_position = params[:checklist][:position].to_i
    if new_position == 0
      position_value = checklists[0].position - 1
    elsif new_position == checklists.length - 1
      position_value = (checklists.length + checklists[new_position].position) / 2
    else
      position_value == (checklists[new_position - 1].position +
                         checklists[new_position].position) / 2
    end
    params[:checklist][:position] = position_value
    if @checklist.update_attributes(params[:checklist])
      redirect_to checklist_url(@checklist)
    else
      flash.now[:notices] = @checklist.errors.full_messages
      render :edit
    end
  end


  def destroy
  end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/views/checklists/edit.html.erb
<%= link_to "<-Back", checklist_url(@checklist) %>

<h2>Edit checklist</h2>

<form action="<%= checklist_url(@checklist) %>" method="POST">
  <input type="hidden" name="_method" value="PUT">
  <input type="hidden" name="authenticity_token"
           value="<%= form_authenticity_token %>">
  <label for="checklist_name">Checklist Name</label>
  <input type="text" id="checklist_name" name="checklist[name]" value="<%= @checklist.name %>">
  <br>
  <label for="checklist_position">Checklist Position</label>
  <select id="checklist_position" name="checklist[position]">
    <% @checklist.card.checklists.length.times do |position| %>
      <option <%= "selected" if @checklist.card.checklists[position].id == @checklist.id %> value="<%= position %>"><%= position + 1 %></option>
    <% end %>
    <br>
  <input type="submit" value="Edit Checklist">
</form>

app/views/checklists/new.html.erb
<%= link_to "<-#{@card.name}", card_url(@card) %>

<h2>Add a checklist</h2>

<form action="<%= card_checklists_url(@card) %>" method="POST">
  <input type="hidden" name="authenticity_token"
           value="<%= form_authenticity_token %>">
  <label for="checklist_name">Checklist Name</label>
  <input type="text" id="checklist_name" name="checklist[name]">
  <input type="submit" value="Add Checklist">
</form>

app/views/checklists/show.html.erb
<%= link_to "<-#{@checklist.card.name}", card_url(@checklist.card) %>
<h2><%= @checklist.name %></h2>

<ul>
<% @checklist.items.each do |item| %>
  <li>
    <% if item.checked %>
      <del><%= item.body %></del>
    <% else %>
      <%= item.body %>
    <% end %>
    <% check_verb = item.checked ? "Uncheck" : "Check" %>
    <%= button_to check_verb, item_url(item), {:method => :put} %>

  </li>
<% end %>
</ul>
<%= render "items/form" %>
<%= link_to "Edit Checklist", edit_checklist_url(@checklist) %>